// This file is generated by Slice Machine. Update with care!

import Kurssit from './Kurssit';
import TextBlock from './TextBlock';

export {
	Kurssit,
	TextBlock,
};

export const components = {
	kurssit: Kurssit,
	text_block: TextBlock,
};
